---

x-redis-env-variable: &redis-env-variable
  REDIS_DSN: ${REDIS_DSN:-redis://redis:6379}


services:
  prestart:
    image: mycostreams/prince-archiver:${TAG:-latest}
    command: ["./prestart.sh"]
    environment:
      <<: [*redis-env-variable]
#    depends_on:
#      db:
#        condition: service_healthy
    networks:
      - default
    volumes:
      - "./scripts/prestart.sh:/app/prestart.sh"



networks:
  default:
