---
x-aws-env-variables: &aws-env-variables
  AWS_ACCESS_KEY_ID: aws-access-key-id
  AWS_SECRET_ACCESS_KEY: aws-access-key-id
  AWS_ENDPOINT_URL: http://localhost.localstack.cloud:4566
  AWS_BUCKET_NAME: mycostreams-raw-data


x-code-volumes: &code-volumes
  volumes:
    - ./prince_archiver:/app/prince_archiver
    - ./alembic/:/app/alembic


x-code-and-data-volumes: &code-and-data-volumes
  volumes:
    - ./prince_archiver:/app/prince_archiver
    - ./alembic/:/app/alembic
    - ./img/example.tif:/data/example.tif
    - /media/admincorentin/5644166e-8493-472e-9f2e-a710ced69b0b/dbx_copy/:/dbx_copy


services:
  prince:
    image: mycostreams/prince-archiver:${TAG:-latest}
    command: ["python", "-m", "prince_archiver.entrypoints.mock_prince.main"]
    environment:
      INTERVAL: ${INTERVAL:-30}
      REDIS_DSN: redis://redis:6379
    depends_on:
      prestart:
        condition: service_completed_successfully
    <<: *code-and-data-volumes


  prestart:
    <<: *code-volumes
    depends_on:
      redis:
        condition: service_healthy


  redis:
    image: redis:7.2.4
    command: ["redis-server", "--save", "60", "1"]
    ports:
      - 127.0.0.1:6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data


networks:
  traefik-public:


volumes:
#  input_data:
#  rabbitmq_data:
  redis_data:
