from setuptools import setup, find_packages

setup(
    name="your_project_name",
    version="0.1.0",
    python_requires=">=3.8",
    install_requires=[
        "aio-pika==9.4.1",
        "aiofiles==23.2.1",
        "alembic==1.13.1",
        "arq==0.25.0",
        "fastapi-slim==0.115.0",
        "httpx==0.27.0",
        "jinja2==3.1.4",
        "pydantic==2.5.3",
        "pydantic-settings==2.1.0",
        "pyyaml==6.0.1",
        "redis==5.2.0",
        "s3fs==2024.3.0",
        "sentry-sdk==1.45.0",
        "sqlalchemy[postgresql-asyncpg]==2.0.29",
        "tenacity==9.0.0",
        "uvicorn==0.30.0",
        "numpy==1.24.0",
        "pandas==2.0.0",
        "tqdm==4.66.0",
        "pytz==2024.2",
    ],
    packages=find_packages(),
    include_package_data=True,
    description="Your project description",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Your Name",
    author_email="your.email@example.com",
    url="https://github.com/yourusername/yourproject",
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.12",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
)
